"""initial schema

Revision ID: 06f064d8d8d3
Revises:
Create Date: 2026-07-24 12:38:14.660338

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "06f064d8d8d3"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actor_role", sa.String(length=40), nullable=False),
        sa.Column("action", sa.String(length=60), nullable=False),
        sa.Column("entity_type", sa.String(length=60), nullable=False),
        sa.Column("entity_id", sa.String(length=60), nullable=True),
        sa.Column("inputs_json", sa.Text(), nullable=True),
        sa.Column("before_json", sa.Text(), nullable=True),
        sa.Column("after_json", sa.Text(), nullable=True),
        sa.Column("success", sa.Boolean(), nullable=False),
        sa.Column("message", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "daily_production_summaries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("production_date", sa.Date(), nullable=False),
        sa.Column("shift", sa.String(length=40), nullable=False),
        sa.Column("drawers_inspected", sa.Integer(), nullable=False),
        sa.Column("drawers_rejected_unique", sa.Integer(), nullable=False),
        sa.Column("drawers_reworked", sa.Integer(), nullable=False),
        sa.Column("drawers_scrapped", sa.Integer(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("drawers_inspected >= 0", name="ck_inspected_nonneg"),
        sa.CheckConstraint(
            "drawers_rejected_unique <= drawers_inspected", name="ck_rejected_le_inspected"
        ),
        sa.CheckConstraint("drawers_rejected_unique >= 0", name="ck_rejected_nonneg"),
        sa.CheckConstraint("drawers_reworked >= 0", name="ck_reworked_nonneg"),
        sa.CheckConstraint("drawers_scrapped >= 0", name="ck_scrapped_nonneg"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("production_date", "shift", name="uq_daily_summary_date_shift"),
    )
    with op.batch_alter_table("daily_production_summaries", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_daily_production_summaries_production_date"),
            ["production_date"],
            unique=False,
        )

    op.create_table(
        "defect_categories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "stations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "defect_cases",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("case_number", sa.String(length=30), nullable=False),
        sa.Column("production_date", sa.Date(), nullable=False),
        sa.Column("detected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("work_order_number", sa.String(length=60), nullable=False),
        sa.Column("drawer_part_reference", sa.String(length=120), nullable=True),
        sa.Column("found_station_id", sa.Integer(), nullable=False),
        sa.Column("possible_source_station_id", sa.Integer(), nullable=True),
        sa.Column("priority", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("disposition", sa.String(length=20), nullable=True),
        sa.Column("repair_action", sa.Text(), nullable=True),
        sa.Column("root_cause", sa.Text(), nullable=True),
        sa.Column("corrective_action", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["found_station_id"],
            ["stations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["possible_source_station_id"],
            ["stations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("defect_cases", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_defect_cases_case_number"), ["case_number"], unique=True
        )
        batch_op.create_index(
            batch_op.f("ix_defect_cases_production_date"), ["production_date"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_defect_cases_work_order_number"), ["work_order_number"], unique=False
        )

    op.create_table(
        "defect_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("defect_case_id", sa.Integer(), nullable=False),
        sa.Column("defect_category_id", sa.Integer(), nullable=False),
        sa.Column("affected_drawer_quantity", sa.Integer(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.CheckConstraint("affected_drawer_quantity >= 1", name="ck_qty_at_least_1"),
        sa.ForeignKeyConstraint(["defect_case_id"], ["defect_cases.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["defect_category_id"],
            ["defect_categories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("defect_case_id", "defect_category_id", name="uq_case_category"),
    )
    op.create_table(
        "defect_photos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("defect_case_id", sa.Integer(), nullable=False),
        sa.Column("stored_filename", sa.String(length=255), nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("content_type", sa.String(length=100), nullable=False),
        sa.Column("uploaded_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["defect_case_id"], ["defect_cases.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "status_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("defect_case_id", sa.Integer(), nullable=False),
        sa.Column("from_status", sa.String(length=30), nullable=True),
        sa.Column("to_status", sa.String(length=30), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("changed_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["defect_case_id"], ["defect_cases.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("status_history")
    op.drop_table("defect_photos")
    op.drop_table("defect_items")
    with op.batch_alter_table("defect_cases", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_defect_cases_work_order_number"))
        batch_op.drop_index(batch_op.f("ix_defect_cases_production_date"))
        batch_op.drop_index(batch_op.f("ix_defect_cases_case_number"))

    op.drop_table("defect_cases")
    op.drop_table("stations")
    op.drop_table("defect_categories")
    with op.batch_alter_table("daily_production_summaries", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_daily_production_summaries_production_date"))

    op.drop_table("daily_production_summaries")
    op.drop_table("audit_log")
    # ### end Alembic commands ###
