"""add source_thread_id and sync_logs

Revision ID: 1d93170b90d6
Revises: f9956ec11ea2
Create Date: 2026-07-27 11:46:14.745769

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1d93170b90d6"
down_revision: Union[str, None] = "f9956ec11ea2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sync_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sync_started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("sync_completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source_url", sa.String(length=255), nullable=False),
        sa.Column("records_fetched", sa.Integer(), nullable=False),
        sa.Column("records_created", sa.Integer(), nullable=False),
        sa.Column("records_updated", sa.Integer(), nullable=False),
        sa.Column("records_skipped", sa.Integer(), nullable=False),
        sa.Column("errors", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("customer_issues", schema=None) as batch_op:
        batch_op.add_column(sa.Column("source_thread_id", sa.String(length=64), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_customer_issues_source_thread_id"), ["source_thread_id"], unique=True
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("customer_issues", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_customer_issues_source_thread_id"))
        batch_op.drop_column("source_thread_id")

    op.drop_table("sync_logs")
    # ### end Alembic commands ###
