"""add cost_per_drawer_at_time to defect_cases

Revision ID: 3d8532f3a9ec
Revises: d459ba03732b
Create Date: 2026-08-21 15:49:37.724886

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3d8532f3a9ec"
down_revision: Union[str, None] = "d459ba03732b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: autogenerate also detected a pre-existing, unrelated drift on
    # auth_sessions.created_at (NOT NULL) - deliberately left out of this
    # migration; Phase 7 touches defect_cases only, per task scope.
    with op.batch_alter_table("defect_cases", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("cost_per_drawer_at_time", sa.Numeric(precision=10, scale=2), nullable=True)
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("defect_cases", schema=None) as batch_op:
        batch_op.drop_column("cost_per_drawer_at_time")
    # ### end Alembic commands ###
