"""add resolved_on_the_spot and skipped_recheck to defect_cases

Revision ID: a3c7e4f19b02
Revises: fc0b5d049466
Create Date: 2026-08-13 16:00:00.000000

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a3c7e4f19b02"
down_revision: Union[str, None] = "fc0b5d049466"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("defect_cases", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "resolved_on_the_spot",
                sa.Boolean(),
                nullable=False,
                server_default=sa.text("0"),
            )
        )
        batch_op.add_column(
            sa.Column(
                "skipped_recheck",
                sa.Boolean(),
                nullable=False,
                server_default=sa.text("0"),
            )
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("defect_cases", schema=None) as batch_op:
        batch_op.drop_column("skipped_recheck")
        batch_op.drop_column("resolved_on_the_spot")
    # ### end Alembic commands ###
