"""add daily_schedules table

Revision ID: d459ba03732b
Revises: b1e2c3d4f5a6
Create Date: 2026-08-21 14:42:08.883202

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d459ba03732b"
down_revision: Union[str, None] = "b1e2c3d4f5a6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: autogenerate also detected a pre-existing, unrelated drift on
    # auth_sessions.created_at (NOT NULL) - deliberately left out of this
    # migration; Phase 6 touches daily_schedules only, per task scope.
    op.create_table(
        "daily_schedules",
        sa.Column("production_date", sa.Date(), nullable=False),
        sa.Column("drawers_scheduled", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("source IN ('sync', 'manual')", name="ck_schedule_source"),
        sa.CheckConstraint("drawers_scheduled >= 0", name="ck_schedule_nonneg"),
        sa.PrimaryKeyConstraint("production_date"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("daily_schedules")
    # ### end Alembic commands ###
