"""add customer issue tables

Revision ID: f9956ec11ea2
Revises: 06f064d8d8d3
Create Date: 2026-07-27 09:21:37.241476

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f9956ec11ea2"
down_revision: Union[str, None] = "06f064d8d8d3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "customer_issue_categories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "customer_issues",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("issue_number", sa.String(length=30), nullable=False),
        sa.Column("reported_date", sa.Date(), nullable=False),
        sa.Column("customer_name", sa.String(length=120), nullable=False),
        sa.Column("order_number", sa.String(length=60), nullable=True),
        sa.Column("issue_category_id", sa.Integer(), nullable=False),
        sa.Column("source_type", sa.String(length=30), nullable=False),
        sa.Column("should_have_caught_at", sa.String(length=120), nullable=True),
        sa.Column("piece_count", sa.Integer(), nullable=False),
        sa.Column("estimated_rework_cost", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("photo_urls", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("linked_defect_case_id", sa.Integer(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.CheckConstraint(
            "source_type IN ('Manufacturing', 'Shipping Damage')",
            name="ck_customer_issue_source_type",
        ),
        sa.CheckConstraint(
            "status IN ('Open', 'Ignored', 'Linked')", name="ck_customer_issue_status"
        ),
        sa.CheckConstraint("piece_count >= 1", name="ck_customer_issue_piece_count_at_least_1"),
        sa.ForeignKeyConstraint(
            ["issue_category_id"],
            ["customer_issue_categories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["linked_defect_case_id"],
            ["defect_cases.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("customer_issues", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_customer_issues_issue_number"), ["issue_number"], unique=True
        )
        batch_op.create_index(
            batch_op.f("ix_customer_issues_reported_date"), ["reported_date"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("customer_issues", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_customer_issues_reported_date"))
        batch_op.drop_index(batch_op.f("ix_customer_issues_issue_number"))

    op.drop_table("customer_issues")
    op.drop_table("customer_issue_categories")
    # ### end Alembic commands ###
