"""add app_settings table and cost_per_drawer_at_time

Revision ID: fc0b5d049466
Revises: 1d93170b90d6
Create Date: 2026-07-28 08:07:46.575684

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fc0b5d049466"
down_revision: Union[str, None] = "1d93170b90d6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_settings",
        sa.Column("key", sa.String(length=60), nullable=False),
        sa.Column("value", sa.String(length=255), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    with op.batch_alter_table("daily_production_summaries", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("cost_per_drawer_at_time", sa.Numeric(precision=10, scale=2), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("daily_production_summaries", schema=None) as batch_op:
        batch_op.drop_column("cost_per_drawer_at_time")

    op.drop_table("app_settings")
    # ### end Alembic commands ###
